/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DAO;
import Controller.KhachHangXLDL;
import Controller.KyGuiXLDL;
import Controller.NhanVienXLDL;
import Model.TblKhachHang;
import Model.TblNhanVien;
import Model.TblThuCungKyGui;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Cong Dan
 */
public class frmKyGui extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmKyGui
     */
    KyGuiXLDL nvDL;
    KhachHangXLDL khDL;
    DefaultTableModel table;
    DAO dao;
    Color mauxanh = new Color(0, 112, 192);

    public frmKyGui() {
        initComponents();
        nvDL = new KyGuiXLDL();
        khDL = new KhachHangXLDL();
        loadhinh(lblSearch, "src\\img\\tk.png");
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        loadNV();
        loadmaKH();
        dao = new DAO("jdbc:sqlserver://localhost:1433;databaseName=QLTC;username=sa;password=123;");
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
    }

    void loadNV() {
        ArrayList<TblThuCungKyGui> list;
        try {
            list = nvDL.getListNV();
            table = (DefaultTableModel) tblKyGui.getModel();
            for (TblThuCungKyGui nv : list) {
                table.addRow(new Object[]{nv.getMaSoThuCung(), nv.getGiong(), nv.getLoai(), nv.getCanNang(), nv.getTinhTrangSK(), nv.getTenKH(), nv.getHinhAnh(),nv.getTrangThai()});
            }
        } catch (SQLException ex) {

        }
    }

    void loadAnh(JLabel lbl, String fileanh) {
        ImageIcon icon = new ImageIcon(fileanh);
        Image image = icon.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        lbl.setIcon(new ImageIcon(image));
    }

    void loadhinh(JLabel lbl, String fileanh) {
        ImageIcon icon = new ImageIcon(fileanh);
        Image image = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        lbl.setIcon(new ImageIcon(image));
    }

    void loadmaKH() {
        try {
            ArrayList<TblKhachHang> KH = khDL.getListNV();
            for (TblKhachHang kh : KH) {
                cboMaKhachHang.addItem(kh);
            }
        } catch (Exception ex) {

        }
    }

    private boolean KTDL() throws HeadlessException {
        StringBuilder sb = new StringBuilder();

        if (tenFile == "") {
            sb.append("Vui lòng chọn file ảnh\n");
        }
        if (txtGiong.getText().equals("")) {
            sb.append("Vui lòng nhập giống\n");
            txtGiong.requestFocus();
        }
        if (txtCanNang.getText().equals("")) {
            sb.append("Vui lòng nhập cân nặng\n");
            txtCanNang.requestFocus();
        }
        if (txtLoai.getText().equals("")) {
            sb.append("Vui lòng nhập loại\n");
            txtLoai.requestFocus();
        }
        if (txtTinhTrangSK.getText().equals("")) {
            sb.append("Vui lòng nhập tình trạng sức khỏe\n");
            txtTinhTrangSK.requestFocus();
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaThuCung = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLoai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTinhTrangSK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCanNang = new javax.swing.JTextField();
        txtGiong = new javax.swing.JTextField();
        lblHinhAnh = new javax.swing.JLabel();
        cboMaKhachHang = new javax.swing.JComboBox<>();
        btnThem = new rojerusan.RSButtonMetro();
        btnSua = new rojerusan.RSButtonMetro();
        btnXoa = new rojerusan.RSButtonMetro();
        btnLuu = new rojerusan.RSButtonMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKyGui = new rojeru_san.complementos.RSTableMetro();
        btnHuy = new rojerusan.RSButtonMetro();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        txtTimKiem = new app.bolivia.swing.JCTextField();
        lblSearch = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Trạng thái");

        cboTrangThai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa nhận", "Đã nhận" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Mã Thú Cưng:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Thông Tin Ký Gửi Thú Cưng");

        txtMaThuCung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMaThuCung.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Tên:");

        txtLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Tình Trạng SK:");

        txtTinhTrangSK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Tên khách Hàng:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Hình Ảnh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Loại:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Cân Nặng:");

        txtCanNang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGiong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboMaKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnThem.setText("Thêm");
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        tblKyGui.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thú cưng", "Tên", "Loại", "Cân nặng", "Tình trạng sức khỏe", "Tên khách hàng", "Hình ảnh", "Trạng thái"
            }
        ));
        tblKyGui.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblKyGui.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblKyGui.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblKyGui.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblKyGui.setRowHeight(25);
        tblKyGui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKyGuiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKyGui);

        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        rSButtonMetro1.setText("Load ảnh");
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setPlaceholder("Tìm kiếm tại đây...");

        lblSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtMaThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addComponent(txtTinhTrangSK, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGap(123, 123, 123)
                .addComponent(txtGiong, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jLabel8)
                .addGap(22, 22, 22)
                .addComponent(cboMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(196, 196, 196)
                .addComponent(jLabel11)
                .addGap(100, 100, 100)
                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1140, 1140, 1140)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1571, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtMaThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7))
                    .addComponent(txtTinhTrangSK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(txtGiong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cboMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11))
                    .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean them, sua, xoa;
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        them = true;
        sua = false;
        xoa = false;
        btnThem.setEnabled(false);
        btnThem.setBackground(Color.GRAY);
        btnSua.setEnabled(false);
        btnSua.setBackground(Color.GRAY);
        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);
    }//GEN-LAST:event_btnThemActionPerformed
    String tenFile = "";

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        them = false;
        sua = true;
        xoa = false;
        btnThem.setEnabled(false);
        btnThem.setBackground(Color.GRAY);
        btnSua.setEnabled(false);
        btnSua.setBackground(Color.GRAY);
        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        them = false;
        sua = false;
        xoa = true;
        btnThem.setEnabled(false);
        btnThem.setBackground(Color.GRAY);
        btnSua.setEnabled(false);
        btnSua.setBackground(Color.GRAY);
        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (them) {
            if (KTDL()) {
                TblKhachHang kh = (TblKhachHang) cboMaKhachHang.getSelectedItem();
                String makhachhang = String.valueOf(kh.getMaKH());
                String hinhanh = tenFile;
                String trangthai=cboTrangThai.getSelectedItem().toString();

                try {
                    Connection conn = dao.getConnect();
                    String caulenh = "INSERT INTO tbl_ThuCungKyGui VALUES(N'" + txtGiong.getText() + "',N'" + txtLoai.getText() + "','" + txtCanNang.getText() + "',N'" + txtTinhTrangSK.getText() + "','" + makhachhang + "','" + tenFile + "',N'" + trangthai + "')";
                    boolean a = dao.Lenh(caulenh, conn);
                    if (a) {
                        tblKyGui.removeAll();
                        table.setRowCount(0);
                        loadNV();
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm KHÔNG thành công");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frmKyGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (sua) {
            int mathucung = Integer.parseInt(txtMaThuCung.getText());
            TblKhachHang kh = (TblKhachHang) cboMaKhachHang.getSelectedItem();
            String makhachhang = String.valueOf(kh.getMaKH());
            String hinhanh = tenFile;
            String trangthai=cboTrangThai.getSelectedItem().toString();
            String caulenh ="";
            if(hinhanh!=null && !hinhanh.equals("")){
                caulenh = "UPDATE tbl_ThuCungKyGui SET Giong=N'" + txtGiong.getText() + "',Loai=N'" + txtLoai.getText() + "',CanNang='" + txtCanNang.getText() + "',TinhTrangSK=N'" + txtTinhTrangSK.getText() + "',MaKH='" + makhachhang + "',HinhAnh='" + tenFile + "',TrangThai=N'" + trangthai + "'where MaSoThuCung=" + mathucung;
            }else{
                caulenh = "UPDATE tbl_ThuCungKyGui SET Giong=N'" + txtGiong.getText() + "',Loai=N'" + txtLoai.getText() + "',CanNang='" + txtCanNang.getText() + "',TinhTrangSK=N'" + txtTinhTrangSK.getText() + "',MaKH='" + makhachhang + "',TrangThai=N'" + trangthai + "'where MaSoThuCung=" + mathucung;
            }
            try {
                Connection conn = dao.getConnect();
                boolean a = dao.Lenh(caulenh, conn);
                if (a) {
                    tblKyGui.removeAll();
                    table.setRowCount(0);
                    loadNV();
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa KHÔNG thành công");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmKyGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (xoa) {
            int mathucung = Integer.parseInt(txtMaThuCung.getText());
            try {
                Connection conn = dao.getConnect();
                String caulenh = "DELETE FROM tbl_ThuCungKyGui WHERE MaSoThuCung=" + mathucung;
                boolean a = dao.Lenh(caulenh, conn);
                if (a) {
                    tblKyGui.removeAll();
                    table.setRowCount(0);
                    loadNV();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa KHÔNG thành công");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmKyGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        txtMaThuCung.setText("");
        txtGiong.setText("");
        txtLoai.setText("");
        txtCanNang.setText("");
        txtTinhTrangSK.setText("");
        loadAnh(lblHinhAnh, "");
        tenFile="";
        tblKyGui.removeAll();
        table.setRowCount(0);
        loadNV();

        btnThem.setEnabled(true);
        btnThem.setBackground(mauxanh);
        btnSua.setEnabled(true);
        btnSua.setBackground(mauxanh);
        btnXoa.setEnabled(true);
        btnXoa.setBackground(mauxanh);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblKyGuiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKyGuiMouseClicked
        // TODO add your handling code here:
        int i = tblKyGui.getSelectedRow();
        hienthitxt(i);
    }//GEN-LAST:event_tblKyGuiMouseClicked
    void hienthitxt(int i) {
        TableModel model = tblKyGui.getModel();
        txtMaThuCung.setText(model.getValueAt(i, 0).toString());
        txtGiong.setText(model.getValueAt(i, 1).toString());
        txtLoai.setText(model.getValueAt(i, 2).toString());
        txtCanNang.setText(model.getValueAt(i, 3).toString());
        txtTinhTrangSK.setText(model.getValueAt(i, 4).toString());
        String cbosub = model.getValueAt(i, 5).toString();
        for (int j = 0; j < cboMaKhachHang.getItemCount(); j++) {
            if (cboMaKhachHang.getItemAt(j).toString().equalsIgnoreCase(cbosub)) {
                cboMaKhachHang.setSelectedIndex(j);
            }
        }
        String src = "src/img/" + model.getValueAt(i, 6).toString();
        loadAnh(lblHinhAnh, src);
        cboTrangThai.setSelectedItem(model.getValueAt(i, 7).toString());
    }
    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        loadAnh(lblHinhAnh, f.toString());
        String fileName = f.getAbsolutePath();
        String newPath = "src/img/";
        File diretory = new File(newPath);
        if (!diretory.exists()) {
            diretory.mkdirs();
        }
        File sourceFile = null;
        File destinationFile = null;
        String extension = fileName.substring(fileName.lastIndexOf('\\') + 1);
        sourceFile = new File(fileName);
        destinationFile = new File(newPath + extension);
        tenFile = extension;
        try {
            Files.copy(sourceFile.toPath(), destinationFile.toPath());
        } catch (IOException ex) {

        }
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        // TODO add your handling code here:
        tblKyGui.removeAll();
        table.setRowCount(0);
        String tk = txtTimKiem.getText();
        ArrayList<TblThuCungKyGui> list;
        try {
            list = nvDL.getListKyGui(tk);
            table = (DefaultTableModel) tblKyGui.getModel();
            for (TblThuCungKyGui nv : list) {
                table.addRow(new Object[]{nv.getMaSoThuCung(), nv.getGiong(), nv.getLoai(), nv.getCanNang(), nv.getTinhTrangSK(), nv.getTenKH(), nv.getHinhAnh(),nv.getTrangThai()});
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_lblSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btnHuy;
    private rojerusan.RSButtonMetro btnLuu;
    private rojerusan.RSButtonMetro btnSua;
    private rojerusan.RSButtonMetro btnThem;
    private rojerusan.RSButtonMetro btnXoa;
    private javax.swing.JComboBox<TblKhachHang> cboMaKhachHang;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblSearch;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rojeru_san.complementos.RSTableMetro tblKyGui;
    private javax.swing.JTextField txtCanNang;
    private javax.swing.JTextField txtGiong;
    private javax.swing.JTextField txtLoai;
    private javax.swing.JTextField txtMaThuCung;
    private app.bolivia.swing.JCTextField txtTimKiem;
    private javax.swing.JTextField txtTinhTrangSK;
    // End of variables declaration//GEN-END:variables
}
